import { normalizePath } from "vite";
import type { Plugin, ResolvedConfig } from "vite";
import fs from "node:fs/promises";
import path from "node:path";

export interface VitePluginSrcUpdateOptions {
  /** Path to the template file that will be (over)written with the asset tags. */
  templateFilePath: string;
  /** Entry points to include. Falls back to the build input when omitted. */
  input?: string[];
  /** Output directory used to prefix built asset paths. Falls back to `build.outDir`. */
  outDir?: string;
  /** Wrap built asset paths in a `{{cdn '...'}}` helper (e.g. BigCommerce Stencil's Handlebars CDN helper). */
  cdn?: boolean;
  /** Inject Vite's HMR client (`@vite/client`) in dev so backend pages get HMR. */
  injectClient?: boolean;
  /** Log additional diagnostic information. */
  verbose?: boolean;
  /** Compute the output without writing the template file. */
  dryRun?: boolean;
  /** Per-extension formatters for the auto-generated header comment. */
  commentTemplates?: Record<string, (comment: string) => string>;
}

const DEFAULT_COMMENT = `IMPORTANT: This component is automatically generated by vite-plugin-src-update.
Do not attempt to modify this file directly, as any changes will be overwritten by the next build.`;

const DEFAULT_COMMENT_TEMPLATES: Record<string, (comment: string) => string> = {
  ".html": (c) => `<!-- ${c} -->`,
  ".liquid": (c) => `{% comment %}\n${c}\n{% endcomment %}`,
  ".hbs": (c) => `{{! ${c.replace(/\n/g, " ")} }}`,
  ".cshtml": (c) => `@* ${c.replace(/\n/g, " ")} *@`,
};

const PREFIX = "[vite-plugin-src-update]";

export default function vitePluginSrcUpdate(
  options: VitePluginSrcUpdateOptions | VitePluginSrcUpdateOptions[]
): Plugin[] {
  return (Array.isArray(options) ? options : [options]).map(createVitePlugin);
}

function createVitePlugin({
  input = [],
  templateFilePath,
  outDir,
  cdn = false,
  injectClient = true,
  verbose = false,
  dryRun = false,
  commentTemplates = DEFAULT_COMMENT_TEMPLATES,
}: VitePluginSrcUpdateOptions): Plugin {
  const resolvedPath = path.resolve(templateFilePath);
  const templateFile = path.basename(resolvedPath);
  const templateExt = path.extname(resolvedPath);
  const formatter = commentTemplates[templateExt] ?? ((c: string) => c);
  const autoComment = formatter(DEFAULT_COMMENT);

  let isBuild = false;
  let resolvedOutDir = outDir;

  const log = (msg: string) => verbose && console.info(PREFIX, msg);
  const logError = (msg: string, err?: unknown) =>
    console.error(PREFIX, msg, err ?? "");

  async function writeTemplate(tags: string[]): Promise<void> {
    const content = [autoComment, ...tags].join("\n") + "\n";
    if (dryRun) {
      log(`[DRY RUN] Would update ${templateFile}:\n${content}`);
      return;
    }
    try {
      // Skip no-op writes so backend file-watchers (Stencil CLI, dotnet watch,
      // Shopify CLI, etc.) don't trigger needless reloads.
      const current = await fs.readFile(resolvedPath, "utf8").catch(() => null);
      if (current === content) {
        log(`${templateFile} unchanged`);
        return;
      }
      await fs.writeFile(resolvedPath, content);
      log(`${templateFile} updated`);
    } catch (err) {
      logError(`Failed to update ${templateFile}:`, err);
    }
  }

  function getAssetPath(fileName: string): string {
    const formatted = normalizePath(path.join(resolvedOutDir ?? "", fileName));
    // e.g. BigCommerce Stencil rewrites `{{cdn '...'}}` to a CDN-hosted URL at render time.
    return cdn ? `{{cdn '${formatted}'}}` : formatted;
  }

  function getInputPaths(config: ResolvedConfig): string[] {
    if (input.length) return input;

    const inputs =
      config.build.rolldownOptions?.input ?? config.build.rollupOptions?.input;

    if (!inputs) return [];
    if (typeof inputs === "string") return [inputs];
    if (Array.isArray(inputs)) return inputs;
    return Object.values(inputs);
  }

  const scriptTag = (src: string) =>
    `<script type="module" src="${src}"></script>`;
  const styleTag = (href: string) =>
    `<link rel="stylesheet" href="${href}">`;

  return {
    name: "vite-plugin-src-update",

    configResolved(config) {
      isBuild = config.command === "build";
      resolvedOutDir ??= path.relative(config.root, config.build.outDir);
      log(`${isBuild ? "build" : "dev"} mode, outDir: ${resolvedOutDir}`);
    },

    configureServer(server) {
      server.httpServer?.once("listening", async () => {
        const addr = server.httpServer?.address();
        if (!addr || typeof addr !== "object") return;

        const protocol = server.config.server.https ? "https" : "http";
        const host = ["", "::", "::1", "0.0.0.0"].includes(addr.address)
          ? "localhost"
          : addr.address;
        const origin = `${protocol}://${host}:${addr.port}`;
        const base = server.config.base || "/";

        const tags = injectClient
          ? [scriptTag(`${origin}${base}@vite/client`)]
          : [];

        for (const p of getInputPaths(server.config)) {
          const rel = path.isAbsolute(p)
            ? path.relative(server.config.root, p)
            : p;
          tags.push(scriptTag(`${origin}${base}${normalizePath(rel)}`));
        }

        await writeTemplate(tags);
      });
    },

    async writeBundle(_options, bundle) {
      if (!isBuild) return;

      const tags = Object.values(bundle)
        .filter(
          (f) =>
            (f.type === "chunk" && f.isEntry) ||
            (f.type === "asset" && f.fileName.endsWith(".css"))
        )
        .map((f) =>
          f.type === "chunk"
            ? scriptTag(getAssetPath(f.fileName))
            : styleTag(getAssetPath(f.fileName))
        );

      await writeTemplate(tags);
    },
  };
}
